### ISSUE TITLE
Submission to Conda-forge

### ISSUE THREAD

**Issue by mahtaao** [neurolib-dev/neurolib#102]
Hi,

I was wondering if you are planning to put the library on Conda-forge? I'm trying to use the library in Julia instead of Python but it's not on the default channel so it's a bit of headache.

Thanks,
Mahta

**Comment by caglorithm** [comment]
Hi Matha,

Thanks for your message! This is a good idea and I will include conda-forge in our future releases! I'm in vacation right now as won't be able to do it in the next few days but I'll let you know, once I'm available!

Just out of curiosity, can I ask what you're working on?

All the best
Caglar

**Comment by mahtaao** [comment]
Hi Caglar,

Thank you for considering my suggestion.
We are reproducing some of the brain models for interoperable meta-models in future. Currently we're coding in Julia and it'd be nice to have a toy-model of neurolib there as a test-bed to avoid compiler complications. To that end, calling neurolib directly from Conda in Julia makes everything much more simple.

Best wishes,
Mahta

**Comment by caglorithm** [comment]
Hi Matha,

sorry for getting back at you so slowly, I've been busy with research... I've tried to pack everything up for conda-forge. Unfortunately, some packages do not exist on conda-forge (`{'jitcdde', 'chspy', 'pypet'}`) which probably means that I won't be able to add neurolib. 

Is this so?
