### ISSUE TITLE
Support `sampling_dt` parameter

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#108]
I was thinking about how to support `sampling_dt` parameter. Reasons:
* for large explorations this would significantly reduce data usage
* in particular for models like thalamus (`dt` should be 0.01) or ALN-thalamus mini-network (I am using 0.005 rn for best results)

Currently, I am leaning towards:
1. introduce `sampling_dt` parameter for all models in `loadDefaultParams.py` (e.g. default value at 10ms)?
1.1 (edit) `sampling_dt = None` would be valid and no subsampling would be done
2. do the actual subsampling in `Model.setOutput` function

this way, I believe all `neurolib` features should work (with exploration / evolution saving subsampled timeseries)

@caglorithm what do you think? I can implement it no problemo, just wanted to be sure it won't break anything and you know the best `neurolib`'s internals...

**Comment by caglorithm** [comment]
I think ]that's a good idea! 
I have been subsampling manually when doing explorations until now. 

Some thoughts:

- This is for the sake of memory usage I believe?
- All the autochunk internals work using the `model.state` so that should be fine as long as we don't touch `setStateVariables()`.
- `model.outputs.t` (==`model.t`) would need to be subsampled as well
- If samling frequency and duration are not commensurable, storing chunkwise outputs will become problematic

**Comment by jajcayn** [comment]
> I have been subsampling manually when doing explorations because of (HDD) storage size. This is for the sake of (RAM) memory usage I believe?

actually both:)

> * Subsampling using `array[::sample_every]` where `sample_every = sample_dt/dt` and `assert isinstance(sample_every, int)`
yup, this should work!

> * All the autochunk internals work using the `model.state` so that should be fine as long as we don't touch `setStateVariables()`.
yes, only `setOutput` function would be altered

> * `model.outputs.t` (==`model.t`) would need to be subsampled as well
yes

> * If sampling frequency and duration are not commensurable, storing / appending chunkwise outputs will become problematic. Should return a warning here or error?
hmm, good point.. I'd firstly assert that duration > sampling_dt and then for chunkwise integration if `sampling_dt` and `chunksize` are not matched, I'd warn the user and automatically change `chunksize` such that it makes sense, i.e. multiples of `sampling_dt`

**Comment by caglorithm** [comment]
> hmm, good point.. I'd firstly assert that duration > sampling_dt and then for chunkwise integration if `sampling_dt` and `chunksize` are not matched, I'd warn the user and automatically change `chunksize` such that it makes sense, i.e. multiples of `sampling_dt`

An option would be to throw an error and let the user enter valid values such that no unintended behaviour is possible... `assert not chunksize % sample_dt`?
