### ISSUE TITLE
How to save results of single simulations and explorations?

### ISSUE THREAD

**Issue by caglorithm** [neurolib-dev/neurolib#12]
Right now, each model just saves its results (meaning the integrated state variables) into their own attributes. Clearly, this is not a good approach since different types of models can have very different number and types of variables. A better approach could be to create a `Result` class. A compromise (to get going) could be to attach an `xarr` object to each model such as `model.results` and let the user access this xarr as they wish.

Similarly, explorations could be stored in this manner. An `exploration` could have `exploration.results` and the user can again decide how to access that. 

Thoughts?

**Comment by jajcayn** [comment]
Definitely tabulated values, for now, I'd use `xarray` as you suggest. the integration could look like
```python
circuit = Circuit(...)
circuit.run(...)
print(circuit.results)
# will print results in a xarray.DataField
circuit.save_results("results.hdf")  # or .nc, or .pkl or .csv if only 2D
```

**Comment by jajcayn** [comment]
actually, the model results are always 2D (`number of state vector variables ` x `time`) so `pandas` is enough there, only exploration results would need multi-d representation, so `xarray`

**Comment by caglorithm** [comment]
I was actually tryig to avoid using `pandas` because I'm not sure if it is fit for timeseries data (I might be wrong). I'm rather used to process results with it. `xarr` however seems to be perfect for this job, especially if you can extend it many more dimensions in (`state variables` x `time` x `parameters`) space. It seems kinda straightforward to save explorations in it or to dump data into an `xarr` from a `pypet` trajectory.

**Comment by jajcayn** [comment]
yup, agreed, we can not use `pandas` and use `xarray` instead for greater compatibility of model results vs. exploration results

**Comment by caglorithm** [comment]
Imagine:

```python
model = Model()
model.run()
model.results # an xarray

circuit = Circuit(*models)
circuit.run()
circuit.results # an xarray
```

All the same syntax for different levels!

**Comment by jajcayn** [comment]
in 6 months we are there :)

**Comment by caglorithm** [comment]
Single simulations save their results into a `.results` object, can be accessed via keys a la `model['x']` or attributes, a la `model.x.` now and also converted to an xr `DataArray` via `model.xr()`.

Exploration results are all saved in `hdf` files and are also accessible via `exploration.results` and a summary accessible as a pandas `DataFrame` via `exploration.dfResults`.
