### ISSUE TITLE
Bug: default input values for WC model

### ISSUE THREAD

**Issue by caglorithm** [neurolib-dev/neurolib#129]
The default parameters of the WC model have this weird difference in E vs I. I'm not sure why this is in there, maybe @ChristophMetzner can tell, but I think this needs to change to be zero for both.

```
    # values of the external inputs
    params.exc_ext = 1.0 * np.ones((params.N,))
    params.inh_ext = np.zeros((params.N,))
```

**Comment by caglorithm** [comment]
Update: this is connected to the fact that the WC model uses heterogeneous paramters, e.g. a **vector** `params.exc_ext` instead of a **scalar** `params.exc_ext` which all other models use. This is of course nice but not coherent with the rest which is why I will sete `params.exc_ext` to `0` and convert `params.exc_ext` to a scalar.

**Comment by caglorithm** [comment]
Update: Found this formula in `S` of the `WC` model that also looks fishy

```
* S_I(c_excinh * excs[no, i - 1]  # input from the excitatory population
  - c_inhinh * inhs[no, i - 1]  # input from within the inhibitory population
  + exc_input_d[no]  # input from other nodes
  + inh_ext)  # external input
```

I think `+ exc_input_d[no] ` should not be inside `S_I()`, correct @ChristophMetzner?

**Comment by ChristophMetzner** [comment]
Yes, you're right. `+ exc_input_d[no]` should not be inside `S_I()` only inside `S_E()`.

**Comment by caglorithm** [comment]
Thanks, will fix.

**Comment by ChristophMetzner** [comment]
Regarding the asymmetry mentioned above. I honestly do not remember why I put that in there. So go ahead and change that too
