### ISSUE TITLE
Simplify `construct_stimulus` and document stimulus in `example-0.5-aln-external-stimulus`

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#165]
A couple of things:
- [x] delete `construct_stimulus` function from `utils.stimulus`; it has three modes and all of them can be achieved with `ModelInput` class:
    - `ac` is the same as `SinusoidalInput`
    - `dc` is the same as `StepInput`
    - `rect` can be easily done with a combination of `ExponentialInput` and `StepInput` with concatenation.. I will create `RectifiedInput` directly in the file
- [x] create a shortcut for creating stimulus to core neurolib models... before it was something like `construct_stimulus("ac", duration=model.params.duration, dt=model.params.dt, stim_amp=1.0, stim_freq=1)`; I propose `SinusoidalInput(amplitude=1.0, period=1000.0).to_model(model)`, such that duration and dt of stimulation will be directly read from `model.params`
- [x] revamp example-0.5-aln-external-stimulus:
    - [x] swap all calls to `construct_stimulus` with new functions
    - [x] create a section about `ModelInput`, what is implemented, how it looks like, what are the options (`to_model`, `as_array`, `as_cubic_splines`)
    - [x] showcase `SummedInput` and `ConcatenatedInput` (need to wait for #162)

**Comment by caglorithm** [comment]
This is so nice. We should schedule a day on which we discuss the new stimulus class together.... When would be good for you?

**Comment by jajcayn** [comment]
today: anytime before 5pm; tomorrow: before interareal meeting; Wednesday: anytime

**Comment by caglorithm** [comment]
Wednesday noon @ 12?

**Comment by jajcayn** [comment]
works, adding to cal
