### ISSUE TITLE
`MultiModel` optimisation / exploration over matrices

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#168]
Use case: you want to explore the phase space over connectivity. Since the connectivity matrix is really a matrix, this won't work with the `ParameterSpace` class, since it only allows scalars as parameters to search over.
Optimization can be done since you need to provide a cost function, and there you can do anything, e.g. build a connectivity matrix and pass it to the model simply with `model.params[*connectivity|local]=<new matrix>` inside a cost function and it will work... 
However, BoxSearch is not usable... BoxSearch simply calls `model.run()` with each new parameter set, but matrices cannot be part of `ParameterSpace`, i.e., parameter set during exploration.

So we need to think of a way how to allow this.

**Comment by caglorithm** [comment]
Each `model.run()` calls `timeIntegration` of a model, meaning that matrices in `params` can be used at that point. No?

**Comment by jajcayn** [comment]
yes, this is not a problem.. the problem is - imagine using a WilsonCowan network with 2 nodes and you want to explore connectivity strength.
Connectivity is a 2x2 `np.ndarray` matrix. So, ideally you would do something like
```python
parameters = ParameterSpace({ "WCnet.connectivity": [np.array([[0.0, 1.0], [1.0, 0,0]]), np.array([[0.0, 2.0], [2.0, 0.0]])],})
```
but that is not allowed. `ParameterSpace` only takes scalars as parameters.

**Comment by caglorithm** [comment]
Parameter space should be able to take arbitrary values, I agree. I thought this would be possible. Workaround would be to pass a scalar and use the scalar in an exploration function to map it to matrices.

**Comment by jajcayn** [comment]
as per workaround: there is no exploration function, correct?
the `BoxSearch` code only does:
```python
...
# get new params from ParameterSpace
runParams = self.getParametersFromTraj(traj)
self.model.params.update(runParams)
self.model.run(**runKwargs)
...
```
there is nothing a user can do

**Comment by caglorithm** [comment]
Nope, there is: 

```python
search = BoxSearch(evalFunction = run, parameterSpace = parameters)
```

**Comment by jajcayn** [comment]
daaaamn, I didn't see that... ok, in that case, all good :)

**Comment by caglorithm** [comment]
Still, thanks for bringing this up. Kind of sucks. I will look into it right now, looking for reasons to procrastinate anyway.

**Comment by jajcayn** [comment]
yes! I mean very very ideally the ParameterSpace would take matrices as well, but I expect problems due to pypet etc... no way to serialize matrices to create DataFrame from the result etc... maybe there is a way, just with a ton of workarounds... the `evalFunction` is a good tip!

**Comment by caglorithm** [comment]
I don't get it. It works for me: 
![image](https://user-images.githubusercontent.com/7763212/123613577-d7165a80-d803-11eb-93fb-50c45ed41348.png)

**Comment by caglorithm** [comment]
Interesting (needs better testing!): 
![image](https://user-images.githubusercontent.com/7763212/123613707-f3b29280-d803-11eb-9f91-1e1dd28fa899.png)

**Comment by jajcayn** [comment]
for me:
```python
parameters = ParameterSpace(
    {
        "WCnet.connectivity": [np.array([[0.0, 1.0], [1.0, 0,0]]), np.array([[0.0, 2.0], [2.0, 0.0]])],
    },
    allow_star_notation=True,
)
search = BoxSearch(net, parameters, filename="test.hdf")
```
leads to:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-6-db444de282ee> in <module>
      3         "WCnet.connectivity": [np.array([[0.0, 1.0], [1.0, 0,0]]), np.array([[0.0, 2.0], [2.0, 0.0]])],
      4     },
----> 5     allow_star_notation=True,
      6 )
      7 search = BoxSearch(net, parameters, filename="test.hdf")

~/.virtualenvs/neurolib/lib/python3.7/site-packages/neurolib/utils/parameterSpace.py in __init__(self, parameters, parameterValues, kind, allow_star_notation)
     36                 parameters, dict
     37             ), "Parameters must be a dict, if no values are given in `parameterValues`"
---> 38             processedParameters = self._processParameterDict(parameters)
     39         else:
     40             # check if all names are strings

~/.virtualenvs/neurolib/lib/python3.7/site-packages/neurolib/utils/parameterSpace.py in _processParameterDict(self, parameters)
    180         if self.kind == "bound":
    181             # check the boundaries
--> 182             self._validate_param_bounds(list(parameters.values()))
    183 
    184         # set all parameters as attributes for easy access

~/.virtualenvs/neurolib/lib/python3.7/site-packages/neurolib/utils/parameterSpace.py in _validate_param_bounds(self, param_bounds)
    142         # check every single parameter bound
    143         for single_bound in param_bounds:
--> 144             self._validate_single_bound(single_bound)
    145 
    146     def _processParameterDict(self, parameters):

~/.virtualenvs/neurolib/lib/python3.7/site-packages/neurolib/utils/parameterSpace.py in _validate_single_bound(single_bound)
    129         ), "An error occured while validating the ParameterSpace of kind 'bound': Only two bounds (min and max) are allowed"
    130         assert (
--> 131             single_bound[1] > single_bound[0]
    132         ), "An error occured while validating the ParameterSpace of kind 'bound': Minimum parameter value can't be larger than the maximum!"
    133 

TypeError: '>' not supported between instances of 'float' and 'list'
```

**Comment by caglorithm** [comment]
> but I expect problems due to pypet etc... no way to serialize matrices to create DataFrame from the result etc

I think it works already. Look at the Cmat and Lengthmat parameters. They are matrices. Or the ALN lookup tables.

**Comment by caglorithm** [comment]
Yup, ok, I think that error above is somehow that the parameter class assumes that the values are boundaries and not entries. This is the case because of optimization where we give boundaries instead of explicit elements. 

Probably due to the fact that there are only 2 values (I haven't checked). this is obviously weird (also we don't need to perform any boundary validation checks for exploration, only for optimization). Haven't looked into the code but will reply when I know more.

**Comment by caglorithm** [comment]
(At least 2 new bugs discovered here :)

**Comment by caglorithm** [comment]
Should we close this issue and fix the bugs? I think it would be resolved then.

**Comment by jajcayn** [comment]
sure, agreed, closing
