### ISSUE TITLE
Neurolib satellite tutorial session at CNS*2022

### ISSUE THREAD

**Issue by sanjayankur31** [neurolib-dev/neurolib#205]
Hi there,

The INCF/OCNS Software WG is organising a set of free online satellite tutorial sessions before CNS*2022. We were wondering if the neurolib team would be open to organising one there too. 

- Location: Online (via Zoom)
- Dates (expected): June 27 - July 1
- registration: free

https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html

Ticket on our tracker here:

https://github.com/OCNS/SoftwareWG/issues/77

---

Could you please let us know in the next few days if possible?

Thanks very much

PS: folks that are part of the software wg: could you please subscribe to the mailing list here to ensure you don't miss out on any announcements. All our discussions remain on GitHub, but we'll send updates/announcements to the list so that stuff doesn't get buried in all the GitHub e-mails we receive:

https://lists.incf.org/cgi-bin/mailman/listinfo/incf-ocns-software-wg

**Comment by sanjayankur31** [comment]
Hello,

Any thoughts about this please?

Cheers,

**Comment by sanjayankur31** [comment]
Ping: @caglorithm @jajcayn ^

**Comment by sanjayankur31** [comment]
Hello!

Yes, June 27 would work fine. We will draft up a schedule once we have heard from all organisers, but we can note that you need priority on June 27.

We're thinking of 3 session lengths:

- short (1.5 hours)
- "half day" (~3 hours)
- "full day" (6--7 hours)


For completeness, here's the complete bit of what we need for organisers at the moment:

---------------------


In general, we think we will have three categories of sessions:

- short: 1.5--2 hours
- "half day": ~3 hours
- "full day": 6--7 hours

We leave the exact duration up to the different organisers.  With the sessions being online, we are extremely flexible :)

We are reaching out to all the organisers now for initial bits of information to help us get started on the schedule. Could you please tell us by the 20th (end of next week):

- what is the expected duration of the session?
- what is the preferred start time of the session (in UTC)?
- are there days that you *cannot* hold the session in the June 27--July 1 interval?
- would you like us to set up zoom meeting rooms for you (for organisers
  that may not have access to institutional zoom etc. subscriptions)?

If you can please set up a web-page for the session and give us the
link, we will put that on the schedule too. This last one is not necessary
just yet. We can also put a post on the Software WG website if you prefer.

We are requesting organisers to record these sessions if possible, and
we will work with the INCF folks to get the recordings put up on the
INCF training space.

**Comment by caglorithm** [comment]
@sanjayankur31 Sorry for the delayed response, I was checking with my holidays. A 1.5 hour session on Monday would be great. I can't do on another day unfortunately :(

**Comment by sanjayankur31** [comment]
Sounds good. Thanks for confirming that the slot works for you. I'm just waiting on a few tutors to confirm their availability, and will then officially announce the schedule.

**Comment by sanjayankur31** [comment]
Hi @caglorithm , I've published the schedule on our website [here](https://ocns.github.io/SoftwareWG/pages/software-wg-satellite-tutorials-at-cns-2022.html), and we'll publish the Zoom links in a different document whose link we'll send out in the registration confirmation e-mail.

Could you please set up a zoom meeting and a web page and send me the links via e-mail at `ankursinha AT fedoraproject DOT org` when you have some time to spare please? If you don't have institutional access to a zoom like platform, I can also set a zoom meeting up for you, please let me know.

**Comment by pgleeson** [comment]
Hi @caglorithm. @sanjayankur31 and I are planning to offer the [Open Source Brain v2](https://docs.opensourcebrain.org/OSBv2/Overview.html) platform to participants of the statellite tutorials as a single integrated place where they can access and run most of the Python based simulators and tools from across the various tutorials. It has an inbuilt [JupyterLab](https://docs.opensourcebrain.org/OSBv2/JupyterLab.html) instance and workspaces created can be saved and reloaded, along with any files generated during the sessions.

I have added the neurolib source/example repo to OSBv2: https://www.v2.opensourcebrain.org/repositories/34, and from there, registered users can create a new workspace from the latest contents of the repository, open it with JupyterLab, run `pip install neurolib` at the terminal, and then they can open and run your notebook examples.

I hope this would be a useful addition for you. I assume you point people to Google Collab generally, but the addition of the OSBv2 option would mean users would have the same environment across multiple tutorials and can mix outputs/scripts from one with others. You shouldn't need to change any of your existing tutorial content for this. 

Let me know if you have any questions.

**Comment by sanjayankur31** [comment]
I'll post regular updates on number of registrations and who intends to attend what so all tutors can prepare accordingly on this ticket here---please keep an eye on it: #106

**Comment by caglorithm** [comment]
@pgleeson thank you for setting it up! We might actually use it over Colab or Binder. Let's see, I like the idea but I am not big a fan of having to register for opening a notebook.

One question: How does it benchmark against Colab or Binder in terms of CPU speed?

**Comment by caglorithm** [comment]
@pgleeson The tool looks awesome, thank you for providing it! Still need to get the hang of it but it looks very useful. Is it possible to add files that are not in the repo?

**Comment by pgleeson** [comment]
Hi @caglorithm. Regarding your questions: there are definitely fewer resources/numbers of nodes available than Google Collab and Binder, but we will be adding more nodes next week for the CNS tutorials. Regarding the processing power of individual nodes, we will ramp these up too (with more memory/speed available), but I've not yet got an insight how they compare to Google/Binder nodes. 

Longer term it will take a lot of tweaking to get a good compromise between number of nodes we make available, what a fresh new workspace is allowed in terms of speed/max memory, and what we have to pay for. But if events like the CNS tutorials  are a success, it will help us get funding for more resources in future.

Re adding files not in the repo, this is simplest through the JupyterLab interface where there is an option to upload files (icon below Run), but you can also browse and add files from other OSB repositories using the resources drawer/column on the left:

<img width="1472" alt="Screenshot 2022-06-21 at 17 23 03" src="https://user-images.githubusercontent.com/1556687/174849730-94a152b9-a17a-4223-a09b-132b986f0da9.png">

**Comment by sanjayankur31** [comment]
@caglorithm could you set up a Zoom link for the session (and optionally a web-page if you want to give some information to users before the session) and please send it to me on my e-mail at `ankursinha AT fedoraproject DOT org`? I can also set up a zoom link for you using my institutional account if you want. Please let me know.

CC: @appukuttan-shailesh

**Comment by caglorithm** [comment]
I will send you a link with the notebooks and the zoom  meeting today! Working on preparing the workspace!

**Comment by sanjayankur31** [comment]
@caglorithm : if you did record the session, can you please share the link so I can send it to the INCF for uploading to the INCF training space?

**Comment by caglorithm** [comment]
@sanjayankur31 Thank you for all the organizing! Really appreciated! Here you go: https://tubcloud.tu-berlin.de/s/3TSwYQC7W87zbtf

**Comment by sanjayankur31** [comment]
Thanks very much, I've shared the link on the website too now and will forward it to the INCF folks.

**Comment by caglarcakan** [comment]
Could you download the file and upload it to the INCF server? The link is only ephemeral and will expire in one month.

**Comment by caglorithm** [comment]
Could you download the file and upload it to the INCF server? The link is only ephemeral and will expire in one month.

**Comment by sanjayankur31** [comment]
Yes, I'll keep a copy. (I don't do the uploading, we need to forward them to the INCF folks who then make the necessary tweaks etc. before uploading to their channels)
