### ISSUE TITLE
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class

### ISSUE THREAD

**Issue by IbrahimK11** [neurolib-dev/neurolib#215]
I have been working with the library for some time now but today I am facing the error above. I am not sure what is causing this, I work on Jupyter Notebook(Anaconda3). 
![Error](https://user-images.githubusercontent.com/54659866/181059903-ac0f9105-f581-4f81-9aa2-93077af14251.PNG)

**Comment by jajcayn** [comment]
Dear @IbrahimK11,

thanks for opening an issue. However, I am afraid this is a bug in `xarray`, not in `neurolib`. As a test, try to open a new notebook with the same python version and virtual environment and just try to import `xarray`, nothing else with:
```python
import xarray as xr
```

My intuition is, that you'll have the same error and then you'll need to raise this issue with `xarray` folks.

**Comment by IbrahimK11** [comment]
I tried with a lower version of numpy and it worked. 

Thank you!
