### ISSUE TITLE
Help Using Neurolib: Finding an easy way to load new data for the model implementation

### ISSUE THREAD

**Issue by JackJeck** [neurolib-dev/neurolib#216]
I've been lately working on my senior project and for this I'm making use of the library "neurolib" which is quite useful for my purposes.

I've noticed that the library provides some data that can be used with some models to simulate whole-brain activity through some code lines:

When I implement a model on a network (structural matrix and length matrix) It's always necessary to specify which data we are going to choose. I understand that using "Dataset" allows me to call between many subjects and choose the correct one; the matrices Cmat, Dmat and some others are numpy arrays (80,80) that can be implemented in the arguments of a model, however, it is natural to want to work with other data, and for this I can extract separately the structural and length matrices (Called F100206, F100206L) with some algorithms and load them with numpy obtaining, for example, two numpy arrays with shape (80, 80).

Now, when I decide to work with these new matrices the models bring some trouble and I have no idea if this has to do with the internal format of the data presented in "Dataset", because according with the suggested scenario, this means, those new data must be dictionaries, and even if I make some line codes to change the format of these, the models still don't work.

One option, I guess, will consist in create a new dataset in the same folder of "gw" and "hcp" data with the same parameters and all, and once this gotten, I can call these data to use with the Cmat and Dmat format.

Now, I wonder if there is an easier way to work with new data?, and if this is not the problem, what's wrong with the type of data I'm working on, Is there something I'm missing?.

Thanks for reading, I really appreciate this.

**Comment by caglorithm** [comment]
Thanks for using neurolib! Just FYI: You can always ask questions on the Github discussion forum so others also learn from the issues you're facing.

if you look at the [code](https://github.com/neurolib-dev/neurolib/blob/master/neurolib/models/aln/model.py#L56) you'll see that the `__init__()` function of the ALN model has several parameters: 

`def __init__(self, params=None, Cmat=None, Dmat=None, lookupTableFileName=None, seed=None)`

You'll have to give your matrices explicit argument names: 

`model = FHNModel(Cmat=F100206, Dmat=F100206L)`

This should work!
