### ISSUE TITLE
Parameter exploration bug: PicklingError

### ISSUE THREAD

**Issue by elmehdiham** [neurolib-dev/neurolib#224]
Hello, 
There is a problem with the Parameter Exploration module, when running the Jupyter notebook "_example-1-aln-parameter-exploration.ipynb_", the line: 

`search.run()
`

give the issue: 

```
PicklingError                             Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 search.run()

File ~\anaconda3\lib\site-packages\neurolib\optimize\exploration\exploration.py:313, in BoxSearch.run(self, **kwargs)
    311 assert self.initialized, "Pypet environment not initialized yet."
    312 self._t_start_exploration = datetime.datetime.now()
--> 313 self.env.run(self.evalFunction)
    314 self._t_end_exploration = datetime.datetime.now()

File ~\anaconda3\lib\site-packages\pypet\environment.py:1806, in Environment.run(self, runfunc, *args, **kwargs)
   1804 self._user_pipeline = False
   1805 self._map_arguments = False
-> 1806 return self._execute_runs(pipeline)

File ~\anaconda3\lib\site-packages\pypet\environment.py:2330, in Environment._execute_runs(self, pipeline)
   2328     sigint_handling.start()
   2329 try:
-> 2330     self._inner_run_loop(results)
   2331 finally:
   2332     self._traj._run_by_environment = False

File ~\anaconda3\lib\site-packages\pypet\environment.py:2463, in Environment._inner_run_loop(self, results)
   2460 while True:
   2462     if self._multiproc:
-> 2463         expanded_by_postproc = self._execute_multiprocessing(start_run_idx, results)
   2464     else:
   2465         # Create a generator to generate the tasks
   2466         iterator = self._make_iterator(start_run_idx)

File ~\anaconda3\lib\site-packages\pypet\environment.py:2777, in Environment._execute_multiprocessing(self, start_run_idx, results)
   2774 task = next(iterator)
   2775 proc = multip.Process(target=_process_single_run,
   2776                       args=(task,))
-> 2777 proc.start()
   2778 process_dict[proc.pid] = proc
   2780 signal_cap = max_signals > 0  # Only signal max_signals times

File ~\anaconda3\lib\multiprocessing\process.py:121, in BaseProcess.start(self)
    118 assert not _current_process._config.get('daemon'), \
    119        'daemonic processes are not allowed to have children'
    120 _cleanup()
--> 121 self._popen = self._Popen(self)
    122 self._sentinel = self._popen.sentinel
    123 # Avoid a refcycle if the target function holds an indirect
    124 # reference to the process object (see bpo-30775)

File ~\anaconda3\lib\multiprocessing\context.py:224, in Process._Popen(process_obj)
    222 @staticmethod
    223 def _Popen(process_obj):
--> 224     return _default_context.get_context().Process._Popen(process_obj)

File ~\anaconda3\lib\multiprocessing\context.py:327, in SpawnProcess._Popen(process_obj)
    324 @staticmethod
    325 def _Popen(process_obj):
    326     from .popen_spawn_win32 import Popen
--> 327     return Popen(process_obj)

File ~\anaconda3\lib\multiprocessing\popen_spawn_win32.py:93, in Popen.__init__(self, process_obj)
     91 try:
     92     reduction.dump(prep_data, to_child)
---> 93     reduction.dump(process_obj, to_child)
     94 finally:
     95     set_spawning_popen(None)

File ~\anaconda3\lib\multiprocessing\reduction.py:60, in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)

PicklingError: Can't pickle <class 'neurolib.utils.parameterSpace.ParameterSpace'>: it's not the same object as neurolib.utils.parameterSpace.ParameterSpace

```

**Comment by riccardoleone1991** [comment]
I had the same problem and re-installing the package in a dedicated Conda environment made the trick and now it is not giving that error anymore. For me, I think the problem was that at first I made a pip install, but then I also did a git clone to have the example folders and so I re-installed everythin. I think pickling wasn't working because I had two instances of the same modules (sorry for the lack of specific terminology, noob here).

**Comment by elmehdiham** [comment]
> I had the same problem and re-installing the package in a dedicated Conda environment made the trick and now it is not giving that error anymore. For me, I think the problem was that at first I made a pip install, but then I also did a git clone to have the example folders and so I re-installed everythin. I think pickling wasn't working because I had two instances of the same modules (sorry for the lack of specific terminology, noob here).

I tried installing the package in a dedicated virtual environment with different python versions but it gave me the same problem. Would you please tell me what python version worked for you?

**Comment by caglorithm** [comment]
Hey! We were discussing to drop support for anything lower than Python 3.8. Have you tried with 3.8? Which operating system are you using?

**Comment by elmehdiham** [comment]
> Hey! We were discussing to drop support for anything lower than Python 3.8. Have you tried with 3.8? Which operating system are you using?

Hello! the operating system is Windows and I tried both python 3.8 and 3.9, but without solution.

Another thing that might be relevant, when I use a dedicated conda environment, I get this error 

`ImportError: DLL load failed while importing utilsextension: The specified module could not be found.`

which I solve by manually installing _pytables_ and then I get the usual Pickling error.

**Comment by caglorithm** [comment]
Ah Windows. Unfortunately, we don't really support windows at all, so I would suggest you try running neurolib using the Linux Subsystem built into Windows. 

I'll close this issue for now, feel free to reopen it in case it makes sense to follow up on it.
