### ISSUE TITLE
func.kuramoto() is shorter than timeseries

### ISSUE THREAD

**Issue by neurolib-dev** [neurolib-dev/neurolib#27]
`kuramoto()` in `neurolib.utils.functions` returns an array that is shorter than its input. This is probably because no padding is done before calculating the value. Needs to be fixed.

**Comment by caglorithm** [comment]
kuramoto() should eventually be ported to the `Signal` class eventually, I guess! 
@jajcayn: does the `Signal` class only "replace" the signal by an updated (processed) version or can it also contain more (time-dependent/time-independent?) information on the signal, like phase or synchrony (in time or overall?).

**Comment by jajcayn** [comment]
yesterday night I implemented `apply` function which applies an arbitrary function over the time dimension.. this can be of course extended to apply any function over any number of dimensions... the result could be stored with `Signal`, but I do not think it is a good idea... but, this way you can compute any measures from the `Signal` class and the result is again, DataArray with same dimensions and labels as the original `Signal`

**Comment by caglorithm** [comment]
Ok that makes sense, I agree! `Signal` contains only `signal` or filtered `signal` but not any extracted information. The line between what is signal processing and feature extraction is a bit blurry I guess!

**Comment by caglorithm** [comment]
fixed
