### ISSUE TITLE
Crash if delays change but model is not reinitialized

### ISSUE THREAD

**Issue by caglorithm** [neurolib-dev/neurolib#43]
If the model it not reinitialized, the maxDelay is not recalculated but assumed to be the same value as before. This leads to a crash if the delays decrease (because state_variables become shorter than the initial_values). Code that reproduces this:

```python
from neurolib.models.aln import ALNModel
from neurolib.utils.loadData import Dataset
ds = Dataset("hcp")
aln = ALNModel(Cmat=ds.Cmat, Dmat=ds.Dmat)

aln.params['signalV'] = 10.0
aln.run(chunkwise=True, chunksize=10000)
aln.params['signalV'] = 1.0
aln.run(chunkwise=True, chunksize=10000)
```

Error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-e10453abeca9> in <module>
      2 aln.run(chunkwise=True, chunksize=10000)
      3 aln.params['signalV'] = 1.0
----> 4 aln.run(chunkwise=True, chunksize=10000)

~/Documents/PhD/projects/neurolib/neurolib/models/model.py in run(self, inputs, onedt, chunkwise, chunksize, bold, append_outputs)
    145                 logging.warn(f"{self.name}: BOLD model not initialized, not simulating BOLD. Use `run(bold=True)`")
    146                 bold = False
--> 147             self.integrate_chunkwise(chunksize=chunksize, bold=bold, append_outputs=append_outputs)
    148             return
    149 

~/Documents/PhD/projects/neurolib/neurolib/models/model.py in integrate_chunkwise(self, chunksize, bold, append_outputs)
    187             currentChunkSize += self.max_delay + 1
    188 
--> 189             self.autochunk(duration=currentChunkSize * dt, append_outputs=append_outputs)
    190 
    191             if bold and self.bold_initialized:

~/Documents/PhD/projects/neurolib/neurolib/models/model.py in autochunk(self, inputs, duration, append_outputs)
    219 
    220         # run integration
--> 221         self.integrate(append_outputs=append_outputs)
    222 
    223         # reset initial conditions to last state

~/Documents/PhD/projects/neurolib/neurolib/models/model.py in integrate(self, append_outputs)
    155         """
    156         # run integration
--> 157         t, *variables = self.integration(self.params)
    158 
    159         # save time array

~/Documents/PhD/projects/neurolib/neurolib/models/aln/timeIntegration.py in timeIntegration(params)
    209     rates_inh[:, startind:] = np.random.standard_normal((N, len(t) - startind))
    210 
--> 211     rates_exc[:, :startind] = rates_exc_init
    212     rates_inh[:, :startind] = rates_inh_init
    213 

ValueError: could not broadcast input array from shape (80,249) into shape (80,2484)
```

**Comment by caglorithm** [comment]
Ways of avoiding this would include:
- Compute new `max_delay` whenever `run()` is called. Problem: if `onedt==True` this would cause a lot of overhead. Maybe it should be only computed if `onedt==False`.
- Compute new `max_delay` whenever "delay-sensitive" (`signalV`, `de`, `di`) parameters got changed. Detect if these parameters were changed by registering "delay-sensitive" parameters (or simply delay parameters) by saving them in the `Model` and checking for the change. 
- Compute new `max_delay` by checking if delay parameters were changed in the `params` object, which is a `dotdict()` and which could detect changes of the delay parameters as well. Delay parameters would have to be registered here as well. 

Registering more parameters makes implementing new models more ugly. However, in the case of no local delays (like in `hopf` and in `fhn`), this could be simply ignored.

**Comment by jajcayn** [comment]
A very very very ideal solution would be to create a `Parameter` base class for all parameters of the model. Then, each specific type of parameter could be subclassed, e.g. `DelayParamater` for any parameter associated with delay, then the checking whether delay specific parameter changed is easy.. Or even better, `DelayParameter` would have some internal state tracking the change. If this internal state would be True, you'd recompute `getMaxDelay` and set internal to False

**Comment by caglorithm** [comment]
I agree, it would be an ideal situation. If the `Parameter` class inherits all `dict` properties and is `dot.accessible`, it would be backwards compatible and the initialization (which is now simply a definition) of a set of Parameters would be as it is right now with only minimal change.

**Comment by jajcayn** [comment]
mmm I meant more like right now, `dotdict` is a collection of parameters, usually float, int or arrays. If we'd introduce the `Parameter` class, the `dotdict` would be a collection (a dict) with `Parameter` as values

I can take a look at it, in my head it's very easy change, I'll try to figure it out:)

**Comment by caglorithm** [comment]
Then I don't get it. Why is a `Parameter` be better than a `float` if the actual parameter is a `float`? Overkill?

**Comment by jajcayn** [comment]
in OOP there is no overkill 😄 
but no, you're maybe right. My idea was along the lines:
```python
class Parameter:
    def __init__(self, value):
        self.val = value
    def __call__(self):
        return self.val


class DelayParameter(Parameter):
    changed = True


# then init would work as
signalV = DelayPrameter(10.0)

if signalV.changed:
    # do something, e.g. get new max delay
    signalV.changed = False

# when getting the parameter value
print(signalV())

# and still the `dotdict` can be dict of Parameters
params = dotdict("signalV": DelayParameter(10.0), <other_params>)
```

not sure, if this is the ideal way to go, but this way you have explicit control over all parameter types that possibly could come in the future...

**Comment by caglorithm** [comment]
Got it. Although this would give us full control over all parameters, I think it's overkill.

Some thoughts in no particular order:
- Defining and changing a parameter becomes a hustle, instead of the simple `model.params['a'] = 1.0`. Existing models would have to be changed (not a big problem if change is limited) and writing a new model becomes more complicated. I would prefer a naive-user solution.
- This would introduce huge problems with `pypet` and `deap`.
- We could end up defining a lot more Parameter classes, like coupling parameters, noise parameters, etc...
- It solves only one issue now but introduces a lot of complexity.

I would prefer a check somewhere else and leave parameter dictionary untouched for now. Honestly, I even don't like the `dotdict` today, because I'd much more prefer a vanilla `dict`.

**Comment by caglorithm** [comment]
Actually, it was meant as a joke but I'd like to look into how `brian` implemented the parameters with units! It might give us some inspiration concerning this issue!

**Comment by caglorithm** [comment]
#49 fixes this issue but in the most naive way: whenever `model.run()` is called, the new max delay is computed. Excessive overhead in `Circuit` can be avoided by calling `model.autochunk()` instead.
