### ISSUE TITLE
Fix Wilson-Cowan variable names

### ISSUE THREAD

**Issue by caglorithm** [neurolib-dev/neurolib#51]
The `WCModel` 's variables are called `x` and `y` instead of `e` and `i`.

**Comment by ChristophMetzner** [comment]
You're right, there is some inconsistency with the variable names. However, I'd rather change the variable names to `e` and `i` consistently, since these are meant to represent an excitatory and an inhibitory neural population. This would also be more consistent with the reference paper.

**Comment by caglorithm** [comment]
Has this been updated, @ChristophMetzner?

**Comment by ChristophMetzner** [comment]
No, I haven't had the time to do that. I will try to fix this during the next week.
