### ISSUE TITLE
Model base class for nodes

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#8]
* one instance for excitatory and inhibitory? As in ALN? or just one actual population, so the E/I node would be represented using two instances?

* what attributes are useful?

* what methods should a node implement?

* other comments?

**Comment by caglorithm** [comment]
Is this not kinda the same question as issue #11 ?

A `node` should be as general as possible. It could be a simple oscillator, a population model, a whole neural network or even a single neuron. 

It should specify how it is integrated by a single timestep, it should define what its output values are and what input parameters are (such that nodes can be connected automagically).

I don't think its necessary to define what a single `atomic` model should be. I can imagine having multiple levels of connectivity across scales. Say, the connectivity matrix in one model can be specified but then if you specify the output of that model, it can in turn be connected to other models.

**Comment by jajcayn** [comment]
love the idea that node could be anything... 

this should serve just as a discussion while #11 should be an issue for implementation
