### ISSUE TITLE
Base class for integration / whole-brain network?

### ISSUE THREAD

**Issue by jajcayn** [neurolib-dev/neurolib#9]
* How exactly should we implement "collection of nodes"?

* I'd go with `Circuit(nodes=[list_of_nodes], SC=SC, delays=delays)` and then `circuit = Circuit(...); circuit.run(t=..., dt=..., sampling_dt=..., ...)`

* the `run()` method would actually run as follows:
    * run would call some python library for SDEs, e.g. `sdeint`
    * each node within `Circuit` would need to implement its own dy/dt update
    * the circuit class would first resolve coupling variables, i.e. variables from nodes that are present as input in other nodes within the network
    * then gather all dy/dt updates for all the nodes

**Comment by caglorithm** [comment]
I agree with your approach! However, I would think of a `Circuit` as a collection of `Model`s. If each `model` specifies its integrand *or* simply the value at the next timestep, and its input and output `channels` (<-- should we go with this name?), the `Circuit` class can simply care about getting each `model` in sync and handing the coupling between them. Again, a `circuit` could specify its input and output channels and could be integrated for a single timestep and ... you know where this would lead to :)
